### ISSUE TITLE
Cannot read nested Map<String, String>

### ISSUE THREAD

**Issue by AnleaR** [Elytrium/java-serializer#9]
I'm trying to create a Kits plugin with great customization flexibility through config.
Here is what I wrote to implement this feature:
```java
public class KitsSettings extends YamlSerializable {

	private static final SerializerConfig CONFIG = new SerializerConfig.Builder().build();

	public KitsSettings() {
		super(KitsSettings.CONFIG);
	}

	public Map<String, KitCache> kits = new HashMap<>();
}
```
KitCache.class:
```java
@Setter
public class KitCache {

	@Getter
	private String name;
	private String material;
	@Getter
	private String displayName;
	private List<String> lore;
	private boolean enchanted;
	@Getter
	private KitType type;
	@Getter
	private int index;
	@Getter
	private int cooldown;
	@Getter
	private int price;
	public Map<Integer, LinkedList<KitItem>> items;

	public KitCache() {
		this.name = "null";
		this.material = "STONE";
		this.displayName = "-";
		this.lore = new ArrayList<>();
		this.enchanted = false;
		this.type = KitType.MONEY;
		this.index = 0;
		this.cooldown = 0;
		this.price = 1;
		this.items = new HashMap<>();
	}

	public KitCache(final String name, final String material, final String displayName, final List<String> lore,
					final boolean enchanted, final KitType type, final int index, final int cooldown,
					final int price) {
		this.name = name;
		this.material = material;
		this.displayName = displayName;
		this.lore = lore;
		this.enchanted = enchanted;
		this.type = type;
		this.index = index;
		this.cooldown = cooldown;
		this.price = price;
		this.items = new HashMap<>();
	}

	public KitCache(final String name, final String material, final String displayName, final List<String> lore,
					final boolean enchanted, final KitType type, final int index, final int cooldown,
					final int price, final Map<Integer, LinkedList<KitItem>> items) {
		this.name = name;
		this.material = material;
		this.displayName = displayName;
		this.lore = lore;
		this.enchanted = enchanted;
		this.type = type;
		this.index = index;
		this.cooldown = cooldown;
		this.price = price;
		this.items = items;
	}
}
```
And here is the class that causes the error (it contains Map<String, String>).
KitItem.class:
```java
@Getter
public class KitItem {

	public String material;
	public String name;
	public List<String> lore;
	public Map<String, String> enchants;
	public Map<String, String> nbts;
	public int amount;

	public KitItem() {
		this.material = "STONE";
		this.name = "-";
		this.lore = new ArrayList<>();
		this.enchants = new HashMap<>();
		this.nbts = new HashMap<>();
		this.amount = 1;
	}

	public KitItem(final String material, final String name, final List<String> lore, final Map<String, String> enchants, final Map<String, String> nbts, final int amount) {
		this.material = material;
		this.name = name;
		this.lore = lore;
		this.enchants = enchants;
		this.nbts = nbts;
		this.amount = amount;
	}
}
```
Serialized config section looks like this:
```yaml
kits:
  start:
    name: "start"
    material: "STONE_SWORD"
    display-name: "&7Start"
    lore:
      - "&8Kit for newbies"
    enchanted: false
    type: GROUP
    index: 0
    cooldown: 1200
    price: 0
    items:
      1:
        - material: "STONE_SWORD"
          name: "&f[&7Starting sword&f]"
          lore: []
          amount: 1
        - material: "STONE_PICKAXE"
          name: "&f[&7Starting pickaxe&f]"
          lore: []
          enchants: {}
          nbts: {}
          amount: 1
        - material: "STONE_AXE"
          name: "&f[&7Starting axe&f]"
          lore: []
          enchants: {}
          nbts: {}
          amount: 1
        - material: "STONE_SHOVEL"
          name: "&f[&7Starting shovel&f]"
          lore: []
          enchants: {}
          nbts: {}
          amount: 1
        - material: "OAK_LOG"
          name: "&f[&7Starting logs&f]"
          lore: []
          enchants: {}
          nbts: {}
          amount: 16
        - material: "COOKED_BEEF"
          name: "&f[&7Starting beef&f]"
          lore: []
          enchants: {}
          nbts: {}
          amount: 8
```
I think the problem is in the complexity of the architecture of my config (F.E.: Map >>> Map >>> Map)
